language: python
python:
    - "2.6"
    - "2.7_with_system_site_packages"
    - "3.2_with_system_site_packages"
    - "3.3"
    - "3.4"
before_install:
    - sudo apt-get install -qq python-numpy
install: python setup.py install
script: nosetests
